server:
  port: 8090
spring:
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
zuul:
  prefix: /api
  routes:
    user-service:
      path: /user/**
      service-id: USER-SERVICE