server:
  port: 8088
spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost/employee_db?autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost